[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "WildRandom"
version = "0.1"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
description = "Wild Random Platform"
requires-python = ">=3.8"